
# Frontend Deployment — React App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-frontend
  namespace: ecom
  labels:
    app: ecom
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom
      tier: frontend
 
  template:
    metadata:
      labels:
        app: ecom
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: ajaydev05/ecom-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: REACT_APP_API_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            
---

# Backend Deployment — Node.js API

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend
  namespace: ecom
  labels:
    app: ecom
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom
  
  template:
    metadata:
      labels:
        app: ecom
        tier: backend
    spec:
      containers:
        - name: backend
          image: ajaydev05/ecom-backend:latest
         
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ecom-secret
                  key: mongo-uri
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: NODE_ENV
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            
---

# MongoDB Deployment — Database

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-mongodb
  namespace: ecom
  labels:
    app: ecom
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom
      tier: database
  
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
         
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecom-secret
                  key: mongo-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecom-secret
                  key: mongo-password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: MONGO_DATABASE
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
          
      volumes:
        - name: mongo-storage
          emptyDir: {}        # Local node storage (data resets if pod restarts)
