apiVersion: v1
kind: Secret
metadata:
  name: ecom-secret
  namespace: ecom
type: Opaque
stringData:
  mongo-uri: "mongodb://admin:password@ecom-mongodb-svc:27017/ecomdb"
  mongo-username: "admin"
  mongo-password: "password"
